### ISSUE TITLE
[NEW REQUEST] CryptPad

### ISSUE THREAD

**Issue by pastudan** [kubesail/apps#1]
Website: https://cryptpad.fr/
GitHub: https://github.com/xwiki-labs/cryptpad
Docker Image: https://hub.docker.com/r/promasu/cryptpad
Has arm64 image: No

**Comment by DrMxrcy** [comment]
https://kubesail.com/template/erulabs/cryptpad/

**Comment by erulabs** [comment]
<3 <3
