### ISSUE TITLE
[NEW REQUEST] Paperless-ngx

### ISSUE THREAD

**Issue by DrMxrcy** [kubesail/apps#4]
**Website**:  https://demo.paperless-ngx.com/
**GitHub**:  https://github.com/paperless-ngx/paperless-ngx
**Docker Image**:  https://hub.docker.com/r/linuxserver/paperless-ngx or https://hub.docker.com/r/paperlessngx/paperless-ngx
**Has arm64 image**: Yes

**Comment by DrMxrcy** [comment]
https://github.com/paperless-ngx/paperless-ngx

**Comment by pastudan** [comment]
https://kubesail.com/template/moshe/paperless-ngx
