### ISSUE TITLE
[NEW REQUEST] lomorage

### ISSUE THREAD

**Issue by erulabs** [kubesail/apps#65]
**Website**: <link> https://lomorage.com/
**GitHub**: <link> https://github.com/lomorage/homepage
**Docker Image**: <link> split between multiple repos: https://hub.docker.com/r/lomorage/arm64-lomorage
**Has arm64 image**: <Yes/No> yes

**Comment by aisnote** [comment]
hi, any updates?

**Comment by DrMxrcy** [comment]
> 

Hey @aisnote I can work on this template for ya

**Comment by DrMxrcy** [comment]
Added @aisnote :)

**Comment by DrMxrcy** [comment]
Added Templates

[arm64] https://kubesail.com/template/jphj/lomorage---arm64

[amd64] https://kubesail.com/template/jphj/Lomorage---amd64
