### ISSUE TITLE
[NEW REQUEST] kavita

### ISSUE THREAD

**Issue by faritvidal** [kubesail/apps#86]
**Website**: https://demo.kavitareader.com/login
**GitHub**: https://github.com/Kareadita/Kavita
**Docker Image**: https://hub.docker.com/r/kizaing/kavita
**Has arm64 image**: YES

**Comment by DrMxrcy** [comment]
Duplicate of #68. I will work on this tomorrow!

**Comment by DrMxrcy** [comment]
@faritvidal Added :) https://kubesail.com/template/jphj/Kavita
